import type { Metadata } from "next";
import Script from "next/script";
import {
  Geist,
  Geist_Mono,
  Patrick_Hand,
  Be_Vietnam_Pro,
} from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const patrickHand = Patrick_Hand({
  variable: "--font-patrick-hand",
  weight: "400",
  subsets: ["latin", "vietnamese", "latin-ext"],
  display: "swap",
});

const beVietnamPro = Be_Vietnam_Pro({
  variable: "--font-be-vietnam-pro",
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
  style: ["normal", "italic"],
  subsets: ["latin", "vietnamese", "latin-ext"],
  display: "swap",
});
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const CHAT_ORIGIN =
    process.env.NEXT_PUBLIC_CHAT_ORIGIN || "http://localhost:3000";
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${beVietnamPro.variable} ${patrickHand.variable} antialiased`}
        suppressHydrationWarning
      >
        <Script
          src={`${CHAT_ORIGIN}/chat-widget.js`}
          strategy="afterInteractive"
          data-src={`${CHAT_ORIGIN}/chat-iframe?site=driver-hupuna`}
        />
        <Script id="hupuna-widget-listener" strategy="afterInteractive">
          {`
            (function(){
              var CHAT_ORIGIN = ${JSON.stringify(CHAT_ORIGIN)};
              window.addEventListener('message', function(e){
                var data = e && e.data;
                if (!data || typeof data !== 'object') return;
                if (data.type === 'HUPUNA_SSO_REQUEST') {
                  try {
                    var iframeOrigin = CHAT_ORIGIN;
                    try {
                      if (window.HupunaChatWidget && window.HupunaChatWidget.iframe && window.HupunaChatWidget.iframe.src) {
                        iframeOrigin = new URL(window.HupunaChatWidget.iframe.src, window.location.href).origin;
                      }
                    } catch {}

                    fetch('/api/sso/issue?aud=chat', { credentials: 'include' })
                      .then(function(r){ return r.json().catch(function(){ return null; }); })
                      .then(function(json){
                        var token = json && json.success && json.token;
                        if (!token) return;
                        var msg = { type: 'HUPUNA_SSO_TOKEN', token: token };
                        try {
                          if (window.HupunaChatWidget && window.HupunaChatWidget.iframe && window.HupunaChatWidget.iframe.contentWindow) {
                            window.HupunaChatWidget.iframe.contentWindow.postMessage(msg, iframeOrigin);
                          } else {
                            var frames = document.getElementsByTagName('iframe');
                            for (var i=0;i<frames.length;i++){
                              var f = frames[i];
                              var src = '';
                              try { src = f.src || ''; } catch {}
                              if (src && src.indexOf(iframeOrigin) === 0) {
                                try { f.contentWindow && f.contentWindow.postMessage(msg, iframeOrigin); } catch {}
                                break;
                              }
                            }
                          }
                        } catch {}
                      })
                      .catch(function(){});
                  } catch {}
                }
              });

              window.HupunaChat = {
                open: function(){ try { window.HupunaChatWidget && window.HupunaChatWidget.open && window.HupunaChatWidget.open(); } catch {} },
                close: function(){ try { window.HupunaChatWidget && window.HupunaChatWidget.close && window.HupunaChatWidget.close(); } catch {} },
                toggle: function(){ try { window.HupunaChatWidget && window.HupunaChatWidget.toggle && window.HupunaChatWidget.toggle(); } catch {} }
              };
            })();
          `}
        </Script>
        {children}
      </body>
    </html>
  );
}
